/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reglement.Avoir;

import Reglement.*;
import Home.App;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author Mlek
 */
public class ReglementAvoirForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReglementForm
     */
    public ReglementAvoirForm() {
         initComponents();
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        buttonGroup1.add(RadioButton_Client);
        buttonGroup1.add(RadioButton_Fournisseur);
        buttonGroup1.add(RadioButton_Passager);

        this.addInternalFrameListener(new InternalFrameAdapter() {
            public void internalFrameClosing(InternalFrameEvent e) {
                int reply = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment quitter ?", "Quitter", JOptionPane.YES_NO_OPTION);
                if (reply == JOptionPane.YES_OPTION) {
                    dispose();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        RadioButton_Passager = new javax.swing.JRadioButton();
        RadioButton_Client = new javax.swing.JRadioButton();
        RadioButton_Fournisseur = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        txt_Res = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Reglement Avoir");

        RadioButton_Passager.setText("Passager");
        RadioButton_Passager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_PassagerActionPerformed(evt);
            }
        });

        RadioButton_Client.setSelected(true);
        RadioButton_Client.setText("Client");
        RadioButton_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_ClientActionPerformed(evt);
            }
        });

        RadioButton_Fournisseur.setText("Fournisseur");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioButton_Passager)
                    .addComponent(RadioButton_Client)
                    .addComponent(RadioButton_Fournisseur))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(RadioButton_Passager)
                .addGap(18, 18, 18)
                .addComponent(RadioButton_Client)
                .addGap(18, 18, 18)
                .addComponent(RadioButton_Fournisseur)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(txt_Res))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton1)))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txt_Res)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButton_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_ClientActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_RadioButton_ClientActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String type_client = "";
        String type_reglement = "";

     

        if (RadioButton_Client.isSelected()) {
            type_client = "Client";
        }
        if (RadioButton_Passager.isSelected()) {
            type_client = "Passager";
        }
        if (RadioButton_Fournisseur.isSelected()) {
            type_client = "Fournisseur";
        }

        if (type_client.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Merci de verifier la selection !");
        } else if (type_client.equals("Client")) {
            ReglementAvoirClientFormDetail c;
            c = new ReglementAvoirClientFormDetail(type_client, type_reglement);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            c.setSize(screenSize.width, screenSize.height);
            c.setFocusable(true);
            c.setVisible(true);
            JDesktopPane ds = getDesktopPane();
            ds = Home.App.d;
            ds.add(c);

            c.moveToFront();
            try {
                c.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            c.show();
            ds.repaint();
        } else if (type_client.equals("Fournisseur")) {
            ReglementAvoirFournisseurFormDetail c;
            c = new ReglementAvoirFournisseurFormDetail(type_client, type_reglement);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            c.setSize(screenSize.width, screenSize.height);
            c.setFocusable(true);
            c.setVisible(true);
            JDesktopPane ds = getDesktopPane();
            ds = Home.App.d;
            ds.add(c);

            c.moveToFront();
            try {
                c.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            c.show();
            ds.repaint();
        } else if (type_client.equals("Passager")) {
            ReglementAvoirPassagerFormDetail c;
            c = new ReglementAvoirPassagerFormDetail(type_client, type_reglement);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            c.setSize(screenSize.width, screenSize.height);
            c.setFocusable(true);
            c.setVisible(true);
            JDesktopPane ds = getDesktopPane();
            ds = Home.App.d;
            ds.add(c);

            c.moveToFront();
            try {
                c.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
            }
            c.show();
            ds.repaint();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RadioButton_PassagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_PassagerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RadioButton_PassagerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButton_Client;
    private javax.swing.JRadioButton RadioButton_Fournisseur;
    private javax.swing.JRadioButton RadioButton_Passager;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_Res;
    // End of variables declaration//GEN-END:variables
}
